### PR TITLE
Support GHC 9.4

### LINKED ISSUE #109: Support GHC 9.4?
I didn't see an issue for this yet so I thought I'd make one. 

`cborg` needs to be updated to support GHC 9.4: https://github.com/well-typed/cborg/pull/304

Ignoring bounds, trying to build `weeder` itself runs into a problem:

```
src/Weeder/Main.hs:43:80: error:
    Module ‘GHC.Iface.Ext.Binary’ does not export ‘NameCacheUpdater’
   |
43 | import GHC.Iface.Ext.Binary ( HieFileResult( HieFileResult, hie_file_result ), NameCacheUpdater( NCU ), readHieFileWithVersion )
   |                                                                                ^^^^^^^^^^^^^^^^^^^^^^^
```

It looks like the name cache updater went away in GHC 9.4:

- 9.2: `readHieFile :: NameCacheUpdater -> FilePath -> IO HieFileResult` https://hackage.haskell.org/package/ghc-9.2.5/docs/GHC-Iface-Ext-Binary.html#v:readHieFile
- 9.4: `readHieFile :: NameCache -> FilePath -> IO HieFileResult` https://hackage.haskell.org/package/ghc-9.4.4/docs/GHC-Iface-Ext-Binary.html

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #109.

This also drops support for GHC 9.2. It doesn't look terribly hard to support both with CPP. But based on previous PRs (#94, #68) it seemed like this approach was preferred. 

I didn't touch any of the Nix stuff. I don't use Nix myself, so I wouldn't know how to verify that my changes worked.

### CODE REVIEW

**Comment by ocharles** [comment]
Fab! Presumably this works as expected on your codebase?

**Comment by tfausak** [comment]
Yup! It worked fine for me.

**Comment by ocharles** [comment]
Excellent! I'll get CI working, then I'll merge and release to Hackage. Thanks for your help!

**Comment by tfausak** [comment]
Thanks!

**Pull request merged**
