### PR TITLE
--version shows hieVersion too

### PR DESCRIPTION
**Pull request by tomjaguarpaw**
I've just started using weeder and I really like it!

The strong coupling to GHC version can be confusing for new users. Showing `hieVersion` in `--version` would go a little way to helping them understand what is going on.

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
And I added another message which I think helps clarify things for users who aren't familiar with HIE files and versions.

**Comment by tomjaguarpaw** [comment]
I don't understand the CI error, but I don't think it's my fault

```
Configuring algebraic-graphs-0.5...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1022:20 in Cabal-3.0.1.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:475:12 in Cabal-3.0.1.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.0.1.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.0.1.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.0.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.0.1.0:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing or private dependencies:
QuickCheck >=2.10 && <2.14

builder for '/nix/store/r9qvzjcqziq8p0chbpc9mf8snhj13lf4-algebraic-graphs-0.5.drv' failed with exit code 1
cannot build derivation '/nix/store/qldj75nyc1ndcprja49ms92rymh5p2q3-weeder-2.1.3.drv': 1 dependencies couldn't be built
error: build of '/nix/store/qldj75nyc1ndcprja49ms92rymh5p2q3-weeder-2.1.3.drv' failed
```

**Comment by ocharles** [comment]
I imagine that's due to us (me) not pinning `nixpkgs`. I'll get CI fixed and then come back to this. Thanks for the PR, it looks good!

**Comment by ocharles** [comment]
Thank you! :t-rex:

**Pull request merged**
