### PR TITLE
Add support for unused types

### PR DESCRIPTION
**Pull request by ryndubei**
This adds optional detection of unused types, enabled by the `unused-types` field in `weeder.toml`. 

Type family instances are not yet supported and are marked as implicit roots - `TypeFamilies.stdout` is a placeholder.

### CODE REVIEW

**Review by ocharles — APPROVED** [review]
This works flawlessly at work, and I can't spot anything wrong with the PR either. Great work!

**Comment by ocharles** [comment]
Actually, I just tried this latest PR against work and I'm getting more weeds about type aliases that are in fact used:

```haskell
type Task a = (String, [Subtask a])


type Subtask a = (String, a)


genericTasks :: forall a tasks. GAll (GAll ((~) a)) tasks => tasks -> [Task a]
genericTasks = genericToListC @(GAll ((~) a)) (genericToListC @((~) a) id)
```

Here both `Task` and `Subtask` are coming out as weeds, but they are used by `genericTasks` (which is not a weed).

Does this PR have type alias support, or is this still a known limitation?

**Comment by ryndubei** [comment]
This was more of a problem with the handling of `HForAllTy` - should be fixed now

**Comment by ocharles** [comment]
Awesome, thanks for the quick fix! I'll try with the latest commit now.

**Comment by ocharles** [comment]
Ok, the next false positive I get is with `StripeSecret` in:

```haskell
module Web.Stripe.Types (module Web.Stripe.Types) where
type StripeSecret = Text

module Web.Stripe.IO (module Web.Stripe.IO) where
import Web.Stripe.Types (Charge, ChargeId, Customer, CustomerId, Error, Source, SourceId, StripeSecret, TokenId)

authCharge ::
  StripeSecret ->
  CustomerId ->
  -- | Specific source id to charge
  SourceId ->
  -- | Amount to charge in USD
  Double ->
  -- | Description to be attached to the charge
  Text ->
  IO (Either Error Charge)
authCharge secret customerId sourceId amount description = do
  let params =
        [ "customer" := customerId
        , "source" := sourceId
        , "amount" := (round (amount * 100) :: Int)
        , "currency" := ("usd" :: String)
        , "description" := description
        , "capture" := ("false" :: String)
        ]
  let req = postWith (stripeDefaults secret) chargesUrl params
  er <- E.try req
  case er of
    Right r ->
      let res = fromJustNote "createCharge: Could not parse response" . decode $ (r ^. responseBody)
       in case r ^. responseStatus . statusCode of
            200 -> return (Right res)
            _ -> return (Left res)
    Left (e :: HttpException) -> E.throwIO e
```

Any idea what's going on with that one?

**Comment by ryndubei** [comment]
Managed to simplify it down to

```haskell
{-# LANGUAGE GADTs #-}

module Spec.Types.StripeIO where

type Secret = String

data A = MkA String Int

f :: Secret -> Int -> Secret
f secret a =
  let _params = MkA mempty a
   in secret
```

with `f` marked as a root.

Reducing it any further in any way eliminates the false positive for Secret, including:
- removing the GADT extension 
- removing either field of MkA
- replacing one of the mentions of String with another type

Fortunately, the problem is limited to type aliases - the false positive also disappears if we change Secret to a newtype. So this could be addressed by adding type signatures to `topLevelAnalysis`.

**Comment by ocharles** [comment]
Awesome, nice digging! Thanks for running with my vague bug report :sweat_smile:

**Comment by ryndubei** [comment]
The false positives with type aliases should all be fixed now, but I've spotted something that could probably be turned into a false positive in the test `OverloadedLabels`.

```haskell
data Label (l :: Symbol) = Get
```

but `Label` does not depend on `Symbol` with `unused-types` enabled, so if we defined `Symbol` locally then it would be a false positive. I think this is because we only call `uses` on datatype constructors, but not on data declarations themselves. 

Since we do not output unused constructors anyway, a simple fix would be to move the call to `uses` to the entire data declaration.

**Comment by ocharles** [comment]
Looking good! I'm down to four false positives now, all of which are of this form:

```haskell
module M where

type ComplianceSubtype = Text

data ComplianceDocument = ComplianceDocument
  { complianceSubtypes :: [ComplianceSubtype]
  }
```

That is, it seems like we're correctly attaching uses of a type synonym in record fields. In this case, `weeder` reports that `ComplianceSubtype` is a weed, but doesn't report that `ComplianceDocument` is a weed. The correct answer is that neither are weeds.

**Review by ocharles — APPROVED** [review]
No more false positives! I think we're good to go, great work! :raised_hands:

**Pull request merged**
