### PR TITLE
Use GHC 9.8 for CI and Nix shell

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by tfausak** [comment]
I don't know how to fix Nix, but if you'd like I could contribute a GitHub Actions workflow for testing against GHC 9.8.

**Comment by ocharles** [comment]
I think I know how to fix it, but I'm away on holiday until next Monday. I'll try and prioritize a release when I'm back, sorry about the wait!

**Comment by tfausak** [comment]
No problem at all! Enjoy your holiday 🏖️

**Comment by ocharles** [comment]
Ok back - time to get this out!

**Pull request merged**
