### PR TITLE
Support GHC 9.6

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by ocharles** [comment]
Thanks! Is this really all that is needed? Usually the GHC API has changed needing weeder changes

**Comment by TristanCacqueray** [comment]
That seems to work yes:

```ShellSession
$ weeder --version

weeder version 2.5.0
hie version 9061
```

**Comment by ocharles** [comment]
Amazing, how convenient!

**Comment by ocharles** [comment]
Amazing, how convenient!

**Comment by TristanCacqueray** [comment]
Not sure why it didn't tripped on the ghc version. Well it built with nixpkgs jailbreak.

**Comment by TristanCacqueray** [comment]
It seems like we need https://github.com/well-typed/cborg/pull/312

**Comment by ocharles** [comment]
Thanks @TristanCacqueray!

**Pull request merged**
