### PR TITLE
change to a one-weed-per-line output format

### PR DESCRIPTION
**Pull request by elaforge**
This makes it easier to read.  Also it lets me suppress duplicates with
uniq.

### CODE REVIEW

**Comment by ocharles** [comment]
I'm fairly allergic to flags and wonder if this could just be the new default output format. I think I'd be fine with that, and it would simplify the codebase.

**Comment by elaforge** [comment]
I also like that idea.  No information is lost with the concise format except the context, and I don't need that since if I'm going to pull the weed I need to go there in the editor anyway.  I added a new commit, not sure if you prefer to squash or not.

**Comment by ocharles** [comment]
I've finally had a chance to try this out and it works great! I do wonder if we're maybe being a little _too_ terse though. How about

```
src/Weeder.hs:403: foo
src/Weeder.hs:401: unused
```

Becomes

```
src/Weeder.hs:403: Defined but not used: `foo`
src/Weeder.hs:401: Defined but not used: `unused`
```

Yes, it's a bit repetitive - but I feel also a bit more friendly. Any thoughts?

**Comment by elaforge** [comment]
I'd still go for maximum terse.  If weeder ever said anything other than "Defined but not used" that would be a different matter, but after the 50th time (or even just 3rd time), it just becomes the noise in between what you're looking for, which is where and what.  At that point a more distinctive divider like |---------| would be less distracting!

Also you might have this in a vim quickfix window or something, where space is tight.  Ok well that's tight on vertical space not horizontal so no big deal.  Maybe someone wants to wrap their quickfix in columns :)  Anyway that's a stretch so it's up to you, I think one per line is already just fine.

**Comment by ocharles** [comment]
Ok, let's go with this then

**Pull request merged**
