### PR TITLE
Allow lens 5.2

### PR DESCRIPTION
**Pull request by TristanCacqueray**
See https://hackage.haskell.org/package/lens-5.2/changelog

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Dear @ocharles , could you please have a look at this PR, it enables building weeder along with the latest lens.

**Comment by ocharles** [comment]
Thanks for the nudge @TristanCacqueray! I'm just upgrading Haskell.nix (https://github.com/ocharles/weeder/pull/107), then I'll rebase this PR and we'll have final CI confirmation of the build. Hopefully should be on Hackage tomorrow.

**Comment by ocharles** [comment]
Released as 2.4.1.

**Comment by TristanCacqueray** [comment]
Thank you!

**Pull request merged**
