### PR TITLE
Replace Dhall with JSON

### PR DESCRIPTION
**Pull request by tfausak**
This also adds support for GHC 9.6 (#115). 

I'm opening this PR mostly for discussion. If it ends up getting merged, that's great, but it's not necessarily my goal. Perhaps these changes are better suited for a fork. 

As much as I like Dhall, it's a pretty heavy dependency for this project. It adds around 100 transitive dependencies, and that can make upgrading to newer GHCs tedious. 

And since Weeder's configuration file format is so simple, I feel like Dhall isn't adding enough value to be worth the cost. So this PR removes Dhall and replaces it with JSON (via Aeson).

### CODE REVIEW

**Comment by ocharles** [comment]
I'm pretty heavily in favor of this. Using Dhall was something of an experiment, and did have the potential to have some nice things like let the user define things like `is-weed` functions, but ultimately regular expressions seem to be perfectly ergonomic. That said, I do hate editing JSON and would still take something config-like - TOML or YAML feel like nice options. They are equally well established config formats. Any thoughts on either of those?

**Comment by tfausak** [comment]
I don't really have any first hand experience with TOML, but it seems nice. I like YAML well enough, but sometimes get frustrated by the many ways it handles strings. It might be annoying to embed regular expressions in YAML, but I suspect most of the time it would be fine. 

I'm not set on JSON though. It's just a format I'm familiar with that happens to have a lighter weight dependency in Haskell.

**Comment by ocharles** [comment]
Cool, `tomland` doesn't look like it has a huge dependency graph. We'd end up with:

```toml
roots = [
  "Foo",
  "Bar.*"
]
type-class-roots = true
```

which seems quite nice.

**Comment by tfausak** [comment]
Any update on this or #118?

**Comment by ocharles** [comment]
No update at the moment I'm afraid, but I will probably go with #118 if you agree that addresses your concerns with the dependency tree size? If so, I suggest we close this PR and focus on #118. I'm working with @ryndubei for Haskell SOC, and may throw that PR his way!

**Comment by ryndubei** [comment]
> No update at the moment I'm afraid, but I will probably go with #118 if you agree that addresses your concerns with the dependency tree size? If so, I suggest we close this PR and focus on #118. I'm working with @ryndubei for Haskell SOC, and may throw that PR his way!

Merged #118 with my branch at ryndubei/weeder@04e8abf04a4b3b5e628f1871e412db503277ab1f - works well with both 9.4 and 9.6.

**Comment by tfausak** [comment]
Sure, I'm fine with #118. My only concern is that `tomland` doesn't officially support GHC 9.6. It happens to build with it, but who knows what will happen with GHC 9.8 and beyond. Perhaps it would be better to use [`toml-reader`](https://hackage.haskell.org/package/toml-reader-0.2.1.0) since Weeder only needs to decode TOML (rather than encode)?

**Comment by ocharles** [comment]
`toml-reader` sounds good to me.

**Comment by tfausak** [comment]
👉 #120

**Pull request closed without merging**
