### PR TITLE
Negative predicates

### PR DESCRIPTION
**Pull request by phadej**
Includes #37

### CODE REVIEW

**Comment by phadej** [comment]
ping

**Comment by ocharles** [comment]
Thanks for the ping. To provide an update, my only hesitation is if we want to bring in this functionality or not. It does slightly complicate configuration. I'll have a think

**Comment by phadej** [comment]
I'd be happy with `roots` becoming some kind of mini-language with set operations: union, difference, complement, intersection, and various primitives: regexp on a symbols, some predicate on instances (currently it's on/off, which is fine too), module exports #40, and others. I hope such thing is easy to embed into Dhall, yet I wont try implementing that myself.

**Comment by ocharles** [comment]
Perhaps you can give me some examples of the kind of things you'd like to be able to say that's too difficult with the current interface?

**Comment by phadej** [comment]
I don't remember what I needed negative predicates for. Maybe it was to say "Everything which isn't defined in `.Internal` modules` are roots.

**Pull request closed without merging**
